name: 'Armbian/build'
description: 'Armbian Linux build framework'
inputs:
  board:
    required: true
  flavor:
    required: true
  release-id:
    required: false
  github-token:
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: chainsx/build
        ref: main
        path: build
    - name: Set env
      shell: bash
      run: |
        if [ ${{ inputs.flavor }} == "debian" ]
        then
          echo "release=sid" >> $GITHUB_ENV
          echo "build-minimal=no" >> $GITHUB_ENV
          echo "build-desktop=no" >> $GITHUB_ENV
          echo "expert=yes" >> $GITHUB_ENV
        elif [ ${{ inputs.flavor }} == "ubuntu" ]
        then
          echo "release=jammy" >> $GITHUB_ENV
          echo "build-minimal=no" >> $GITHUB_ENV
          echo "build-desktop=no" >> $GITHUB_ENV
          echo "expert=yes" >> $GITHUB_ENV
        fi
    - name: Build
      shell: bash
      run: |
      
        cd ./build
        touch .ignore_changes
        
        #if [ ${{ inputs.branch }} == "edge" ]; then
        #  sed -i "s|tag:th1520-v6.7-rc1|branch:th1520-v6.7-rc3|g" config/sources/families/thead.conf
        #  echo 'CONFIG_RISV_THEAD_LIGHT_CPUFREQ=y' >> config/kernel/linux-thead-edge.config
        #  echo 'CONFIG_LIGHT_AON_PD=y' >> config/kernel/linux-thead-edge.config
        #  echo 'CONFIG_CLK_LIGHT_FM=y' >> config/kernel/linux-thead-edge.config
        #  sed -i "s|# CONFIG_RTW88_8723DS is not set|CONFIG_RTW88_8723DS=m|g" config/kernel/linux-thead-edge.config
        #fi
        
        git status
        docker pull ghcr.io/armbian/docker-armbian-build:armbian-ubuntu-jammy-latest
             
        ./compile.sh \
        BOARD=${{ inputs.board }} \
        BRANCH=${{ inputs.branch }} \
        RELEASE=${{ env.release }} \
        BUILD_MINIMAL=${{ env.build-minimal }} \
        BUILD_DESKTOP=${{ env.build-desktop }} \
        KERNEL_CONFIGURE=no \
        EXPERT=${{ env.expert }} \
        SHARE_LOG=yes \
        DEBUG=yes \
        COMPRESS_OUTPUTIMAGE=sha,gpg,xz
    - name: Upload
      if: inputs.release-id != '' && inputs.github-token != ''
      uses: xresloader/upload-to-github-release@v1
      env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
        file: "./build/output/images/*.img.xz;./build/output/images/*.img.xz.sha;./build/output/debs/linux-*.deb;./build/output/config/*"
        draft: false
    - name: Rollback release
      if: failure() && inputs.release-id != '' && inputs.github-token != ''
      uses: author/action-rollback@stable
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
    - name: Delete cache
      if: inputs.release-id != '' && inputs.github-token != ''
      shell: bash
      run: |
        sudo rm -rf ./build
