name: 'Armbian/build'
description: 'Armbian Linux build framework'
inputs:
  board:
    required: true
  flavor:
    required: true
  release-id:
    required: false
  github-token:
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: 150balbes/build
        ref: risc-v
        path: build
    - name: Set env
      shell: bash
      run: |
        if [ ${{ inputs.flavor }} == "debian" ]
        then
          echo "release=sid" >> $GITHUB_ENV
          echo "build-minimal=yes" >> $GITHUB_ENV
          echo "build-desktop=no" >> $GITHUB_ENV
          echo "expert=no" >> $GITHUB_ENV
        elif [ ${{ inputs.flavor }} == "ubuntu" ]
        then
          echo "release=jammy" >> $GITHUB_ENV
          echo "build-minimal=yes" >> $GITHUB_ENV
          echo "build-desktop=no" >> $GITHUB_ENV
          echo "expert=no" >> $GITHUB_ENV
        fi
    - name: Build
      shell: bash
      run: |
        cd ./build
        touch .ignore_changes
        sed -i "s|enable_extension \"grub-riscv64-d1\"|#enable_extension \"grub-riscv64-d1\"|g" config/sources/families/d1.conf
        sed -i "s|#BOOTFS_TYPE=fat|BOOTFS_TYPE=fat|g" config/sources/families/d1.conf
        sed -i "s|#BOOTSIZE=512|BOOTSIZE=512|g" config/sources/families/d1.conf
        sed -i "s|https://github.com/smaeul/linux|https://github.com/tekkamanninja/linux|g" config/sources/families/d1.conf
        sed -i "s|riscv/d1-wip|allwinner_nezha_d1_devel|g" config/sources/families/d1.conf
        
        rm config/kernel/linux-d1-current.config
        wget https://github.com/tekkamanninja/linux/raw/allwinner_nezha_d1_devel/arch/riscv/configs/nezha_fedora_defconfig -O config/kernel/linux-d1-current.config
        
        ./compile.sh \
        BOARD=${{ inputs.board }} \
        BRANCH=${{ inputs.branch }} \
        RELEASE=${{ env.release }} \
        BUILD_MINIMAL=${{ env.build-minimal }} \
        BUILD_DESKTOP=${{ env.build-desktop }} \
        KERNEL_ONLY=no \
        KERNEL_CONFIGURE=no \
        EXPERT=${{ env.expert }} \
        COMPRESS_OUTPUTIMAGE=sha,gpg,xz
    - name: Upload
      if: inputs.release-id != '' && inputs.github-token != ''
      uses: xresloader/upload-to-github-release@v1
      env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
        file: ./build/output/images/*
        draft: false
    - name: Rollback release
      if: failure() && inputs.release-id != '' && inputs.github-token != ''
      uses: author/action-rollback@stable
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
    - name: Delete cache
      if: inputs.release-id != '' && inputs.github-token != ''
      shell: bash
      run: |
        sudo rm -rf ./build
