name: 'Armbian/build'
description: 'Armbian Linux build framework'
inputs:
  board:
    required: true
  flavor:
    required: true
  release-id:
    required: false
  github-token:
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: armbian/build
        ref: main
        path: build
    - name: Set env
      shell: bash
      run: |
        if [ ${{ inputs.flavor }} == "debian" ]
        then
          echo "release=sid" >> $GITHUB_ENV
          echo "build-minimal=no" >> $GITHUB_ENV
          echo "build-desktop=yes" >> $GITHUB_ENV
          echo "desktop-environment=gnome" >> $GITHUB_ENV
          echo "desktop-environment-config-name=config_base" >> $GITHUB_ENV
          echo "expert=no" >> $GITHUB_ENV
        elif [ ${{ inputs.flavor }} == "ubuntu" ]
        then
          echo "release=jammy" >> $GITHUB_ENV
          echo "build-minimal=no" >> $GITHUB_ENV
          echo "build-desktop=yes" >> $GITHUB_ENV
          echo "desktop-environment=gnome" >> $GITHUB_ENV
          echo "desktop-environment-config-name=config_base" >> $GITHUB_ENV
          echo "expert=yes" >> $GITHUB_ENV
          echo "desktop_appgroups_selected=\"3dsupport desktop_tools browsers\"" >> $GITHUB_ENV
        fi
    - name: Build
      shell: bash
      run: |
        cd ./build
        touch .ignore_changes
        #sed -i "s|https://github.com/150balbes/rockchip-kernel|https://github.com/chainsx/linux-rockchip|g" config/sources/families/media.conf
        #sed -i "s|commit:9db2691ddfbdc7013d507df665f3e038eea7bf93|branch:rk-5.10-rkr6|g" config/sources/families/media.conf
        #sed -i "s|rk3588s-roc-pc.dtb|rk3588s-roc-rk3588s-pc-v12.dtb|g" config/boards/station-m3.csc
        #sed -i "s|# CONFIG_RTL8821CU is not set|CONFIG_RTL8821CU=y|g" config/kernel/linux-media-legacy.config
        #sed -i "s|CONFIG_THERMAL_DEFAULT_GOV_POWER_ALLOCATOR=y|# CONFIG_THERMAL_DEFAULT_GOV_POWER_ALLOCATOR is not set|g" config/kernel/linux-media-legacy.config
        #sed -i "s|# CONFIG_THERMAL_DEFAULT_GOV_STEP_WISE is not set|CONFIG_THERMAL_DEFAULT_GOV_STEP_WISE=y|g" config/kernel/linux-media-legacy.config
        
        if [ ${{ inputs.board }} == "station-m3" ]; then
          mkdir userpatches
          cp ../userpatches/customize-image.sh userpatches/customize-image.sh
        fi
        
        git status
        docker pull ghcr.io/armbian/docker-armbian-build:armbian-ubuntu-jammy-latest
             
        ./compile.sh \
        BOARD=${{ inputs.board }} \
        BRANCH=${{ inputs.branch }} \
        RELEASE=${{ env.release }} \
        BUILD_MINIMAL=${{ env.build-minimal }} \
        BUILD_DESKTOP=${{ env.build-desktop }} \
        KERNEL_CONFIGURE=no \
        DESKTOP_ENVIRONMENT=${{ env.desktop-environment }} \
        DESKTOP_ENVIRONMENT_CONFIG_NAME=${{ env.desktop-environment-config-name }} \
        DESKTOP_APPGROUPS_SELECTED=${{ env.desktop_appgroups_selected }} \
        EXPERT=${{ env.expert }} \
        SHARE_LOG=no \
        DEBUG=yes \
        COMPRESS_OUTPUTIMAGE=sha,gpg,xz
    - name: Upload
      if: inputs.release-id != '' && inputs.github-token != ''
      uses: xresloader/upload-to-github-release@v1
      env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
        file: "./build/output/images/*.img.xz;./build/output/images/*.img.xz.sha;./build/output/debs/linux-*.deb"
        draft: false
    - name: Rollback release
      if: failure() && inputs.release-id != '' && inputs.github-token != ''
      uses: author/action-rollback@stable
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
    - name: Delete cache
      if: inputs.release-id != '' && inputs.github-token != ''
      shell: bash
      run: |
        sudo rm -rf ./build
