name: 'Armbian/build'
description: 'Armbian Linux build framework'
inputs:
  board:
    required: true
  flavor:
    required: true
  release-id:
    required: false
  github-token:
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: armbian/build
        ref: nightly
        path: build
    - name: Set env
      shell: bash
      run: |
        if [ ${{ inputs.flavor }} == "debian" ]
        then
          echo "release=sid" >> $GITHUB_ENV
          echo "build-minimal=no" >> $GITHUB_ENV
          echo "build-desktop=yes" >> $GITHUB_ENV
          echo "desktop-environment=gnome" >> $GITHUB_ENV
          echo "desktop-environment-config-name=config_base" >> $GITHUB_ENV
          echo "expert=no" >> $GITHUB_ENV
        elif [ ${{ inputs.flavor }} == "ubuntu" ]
        then
          echo "release=jammy" >> $GITHUB_ENV
          echo "build-minimal=no" >> $GITHUB_ENV
          echo "build-desktop=yes" >> $GITHUB_ENV
          echo "desktop-environment=gnome" >> $GITHUB_ENV
          echo "desktop-environment-config-name=config_base" >> $GITHUB_ENV
          echo "expert=yes" >> $GITHUB_ENV
          if [ ${{ inputs.board }} == "rock-5b" ] || [ ${{ inputs.board }} == "station-m3" ] || [ ${{ inputs.board }} == "orangepi5" ]
          then
            if [ ${{ inputs.branch }} == "legacy" ]
            then
              echo "desktop_appgroups_selected=\"desktop_tools\"" >> $GITHUB_ENV
            else
              echo "desktop_appgroups_selected=\"3dsupport browsers chat desktop_tools editors email internet multimedia office programming remote_desktop\"" >> $GITHUB_ENV
            fi
          else
            echo "desktop_appgroups_selected=\"3dsupport browsers chat desktop_tools editors email internet multimedia office programming remote_desktop\"" >> $GITHUB_ENV
          fi
        fi
    - name: Build
      shell: bash
      run: |
        cd ./build
        touch .ignore_changes
        #mkdir -p ./config/desktop/jammy/appgroups/panfork-mesa/sources/apt/
        wget https://github.com/chainsx/armbian-rock5b/raw/master/panfork/panfork-mesa.gpg -O config/cli/jammy/main/config_desktop/sources/apt/panfork-mesa.gpg
        wget https://github.com/chainsx/armbian-rock5b/raw/master/panfork/panfork-mesa.source -O config/cli/jammy/main/config_desktop/sources/apt/panfork-mesa.source
        
        sed -i "s|# CONFIG_SENSORS_PWM_FAN is not set|CONFIG_SENSORS_PWM_FAN=y|g" config/kernel/linux-rockchip-rk3588-legacy.config
        sed -i "s|ext4|fat|g" config/boards/rock-5b.wip
       
        rm config/sources/families/media.conf
        wget https://github.com/chainsx/armbian-station-m3/raw/master/media.conf -O config/sources/families/media.conf
        #sed -i "s|kernel-5.10|kernel-5.10-next|g" config/sources/families/media.conf
        
        ./compile.sh \
        BOARD=${{ inputs.board }} \
        BRANCH=${{ inputs.branch }} \
        RELEASE=${{ env.release }} \
        BUILD_MINIMAL=${{ env.build-minimal }} \
        BUILD_DESKTOP=${{ env.build-desktop }} \
        KERNEL_ONLY=no \
        KERNEL_CONFIGURE=no \
        DESKTOP_ENVIRONMENT=${{ env.desktop-environment }} \
        DESKTOP_ENVIRONMENT_CONFIG_NAME=${{ env.desktop-environment-config-name }} \
        DESKTOP_APPGROUPS_SELECTED=${{ env.desktop_appgroups_selected }} \
        EXPERT=${{ env.expert }} \
        BOARD_FIRMWARE_INSTALL="-full" \
        COMPRESS_OUTPUTIMAGE=sha,gpg,xz
    - name: Upload
      if: inputs.release-id != '' && inputs.github-token != ''
      uses: xresloader/upload-to-github-release@v1
      env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
        file: ./build/output/images/*
        draft: false
    - name: Rollback release
      if: failure() && inputs.release-id != '' && inputs.github-token != ''
      uses: author/action-rollback@stable
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
    - name: Delete cache
      if: inputs.release-id != '' && inputs.github-token != ''
      shell: bash
      run: |
        sudo rm -rf ./build
