name: 'Armbian/build'
description: 'Armbian Linux build framework'
inputs:
  board:
    required: true
  flavor:
    required: true
  release-id:
    required: false
  github-token:
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: chainsx/armbian-riscv-build
        ref: main
        path: build
    - name: Set env
      shell: bash
      run: |
        if [ ${{ inputs.flavor }} == "debian" ]
        then
          echo "release=sid" >> $GITHUB_ENV
          echo "build-minimal=yes" >> $GITHUB_ENV
          echo "build-desktop=no" >> $GITHUB_ENV
          echo "expert=no" >> $GITHUB_ENV
        elif [ ${{ inputs.flavor }} == "ubuntu" ]
        then
          echo "release=jammy" >> $GITHUB_ENV
          echo "build-minimal=yes" >> $GITHUB_ENV
          echo "build-desktop=no" >> $GITHUB_ENV
          echo "expert=no" >> $GITHUB_ENV
        fi
    - name: Build
      shell: bash
      run: |
        cd ./build
        touch .ignore_changes
        
        #wget https://github.com/chainsx/armbian-d1-build/releases/download/toolchain/riscv64-linux-x86_64-20200528.tar.xz -O /opt/riscv64-gcc.tar.xz
        #tar -xvf /opt/riscv64-gcc.tar.xz -C /opt
        #mv /opt/riscv64-linux-x86_64-20200528 /opt/riscv64-compiler
        
        #sed -i "s|riscv64-linux-gnu-|/opt/riscv64-compiler/bin/riscv64-unknown-linux-gnu-|g" config/sources/riscv64.conf
    
        ./compile.sh \
        BOARD=${{ inputs.board }} \
        BRANCH=${{ inputs.branch }} \
        RELEASE=${{ env.release }} \
        BUILD_MINIMAL=${{ env.build-minimal }} \
        BUILD_DESKTOP=${{ env.build-desktop }} \
        KERNEL_ONLY=no \
        KERNEL_CONFIGURE=no \
        EXPERT=${{ env.expert }} \
        COMPRESS_OUTPUTIMAGE=sha,gpg,xz
    - name: Upload
      if: inputs.release-id != '' && inputs.github-token != ''
      uses: xresloader/upload-to-github-release@v1
      env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
        file: ./build/output/images/*
        draft: false
    - name: Rollback release
      if: failure() && inputs.release-id != '' && inputs.github-token != ''
      uses: author/action-rollback@stable
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
    - name: Delete cache
      if: inputs.release-id != '' && inputs.github-token != ''
      shell: bash
      run: |
        sudo rm -rf ./build
